//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cygnet.ProjMan.EFData.ViewModels
{
    using DataSource;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee_detailsModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_detailsModel()
        {
            this.additional_information = new HashSet<additional_informationModel>();
            this.certifications = new HashSet<certificationsModel>();
            this.educational_qualifications = new HashSet<educational_qualificationsModel>();
            this.employee_refcheck = new HashSet<employee_refcheckModel>();
            this.other_details = new HashSet<other_detailsModel>();
            this.epfo_details = new HashSet<epfo_detailsModel>();
            this.esic_details = new HashSet<esic_detailsModel>();
            this.family_details = new HashSet<family_detailsModel>();
            this.feedback = new HashSet<feedbackModel>();
            this.prev_employ_1 = new HashSet<prev_employ_1Model>();
            this.previous_company_details = new HashSet<previous_company_detailsModel>();
            this.references = new HashSet<referencesModel>();
        }
    
        public int employee_id { get; set; }
        [Required(ErrorMessage = "Employee Code is required")]
        public string employee_code { get; set; }
        public string designation { get; set; }
        [Required(ErrorMessage = "Designation is required")]
        public Nullable<int> roleID { get; set; }
        public string department { get; set; }
        [Required(ErrorMessage = "Department is required")]
        public Nullable<int> DeptID { get; set; }
        [Required(ErrorMessage = "Firstname is required")]
        [RegularExpression("^[a-zA-Z/s]+$", ErrorMessage = "Firstname should not contain numbers or special characters")]
        public string firstname { get; set; }
        [Required(ErrorMessage = "Middlename is required")]
        [RegularExpression("^[a-zA-Z/s]+$", ErrorMessage = "Middlename should not contain numbers or special characters")]
        public string middlename { get; set; }
        [Required(ErrorMessage = "Lastname is required")]
        [RegularExpression("^[a-zA-Z/s]+$", ErrorMessage = "Lastname should not contain numbers or special characters")]
        public string surname { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        public string gender { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> date_of_birth { get; set; }
        [Required(ErrorMessage = "Date of Joining is required")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> date_of_joining { get; set; }
        [Required(ErrorMessage = "Marital Status is required")]
        public Nullable<int> marital_status { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> marriage_anniversary { get; set; }
        public string blood_group { get; set; }
        [Required(ErrorMessage = "Contact Number is required")]
        [RegularExpression("^([+][9][1]|[9][1]|[0]){0,1}([7-9]{1})([0-9]{9})$", ErrorMessage = "Please enter a valid 10 digit Mobile Number")]
        public string mobile_number { get; set; }
        [RegularExpression("^([+][9][1]|[9][1]|[0]){0,1}([0-9]{1})([0-9]{9})$", ErrorMessage = "Please enter a valid Phone Number")]
        public string home_number { get; set; }
        [RegularExpression("^([+][9][1]|[9][1]|[0]){0,1}([0-9]{1})([0-9]{9})$", ErrorMessage = "Please enter a valid Phone Number")]
        public string alternate_number { get; set; }
        [Required(ErrorMessage = "Emergency Number is required")]
        [RegularExpression("^([+][9][1]|[9][1]|[0]){0,1}([0-9]{1})([0-9]{9})$", ErrorMessage = "Please enter a valid Phone Number")]
        public string emergency_number { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage = "Please provide a valid Email-ID")]
        public string email_id { get; set; }
        [Required(ErrorMessage = "Permanent Address is required")]
        public string permanent_address { get; set; }
        [Required(ErrorMessage = "Temporary Address is required")]
        public string temporary_address { get; set; }
        [Required(ErrorMessage = "Aadhar Card is required")]
        [RegularExpression("^([0-9]{12})$", ErrorMessage = "Please enter a valid Aadhar Number (Contains 12 digits without alphabets and special characters)")]
        public string aadhar_card { get; set; }
        [RegularExpression("^([A-Za-z]{5})([0-9]{4})([A-Za-z]{1})$", ErrorMessage = "Please enter a valid PAN Number (Eg. ABCDE1234A)")]
        public string pan_card { get; set; }
        [RegularExpression("^([A-Za-z]{1})([0-9]{7})$", ErrorMessage = "Please enter a valid Passport Number (Eg. A1234567)")]
        public string passport_number { get; set; }
        public Nullable<System.DateTime> passport_validity { get; set; }
        [RegularExpression("^([A-Za-z]{3})([0-9]{7})$", ErrorMessage = "Please enter a valid Election Card Number (Eg. AAA1234567)")]
        public string election_card { get; set; }
        [RegularExpression("^([A-Za-z]{2})([0-9]{1,2})([A-Za-z]{1,2})([0-9]{4})$", ErrorMessage = "Please enter a valid Vehicle Number (Eg. GJ01AA1234)")]
        public string vehicle_number { get; set; }
        public string single_bank_account { get; set; }
        public string ifs_code { get; set; }
        public string allergies { get; set; }
        public string known_ailments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<additional_informationModel> additional_information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certificationsModel> certifications { get; set; }
        public virtual department department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<educational_qualificationsModel> educational_qualifications { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_refcheckModel> employee_refcheck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<other_detailsModel> other_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<epfo_detailsModel> epfo_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<esic_detailsModel> esic_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<family_detailsModel> family_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedbackModel> feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prev_employ_1Model> prev_employ_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<previous_company_detailsModel> previous_company_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referencesModel> references { get; set; }
    }
}
