//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cygnet.ProjMan.EFData.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class feedbackModel
    {
        public int feedback_id { get; set; }
        public int employee_id { get; set; }
        [Required(ErrorMessage = "HR Manual field is required")]
        public string hr_manual { get; set; }
        [Required(ErrorMessage = "CIMS ID/Password field is required")]
        public string cims_idpassword { get; set; }
        [Required(ErrorMessage = "Books field is required")]
        public string books { get; set; }
        [Required(ErrorMessage = "Library Card field is required")]
        public string library_card { get; set; }
        [Required(ErrorMessage = "HR Any Other field is required")]
        public string hr_anyother { get; set; }
        [Required(ErrorMessage = "Identity Card field is required")]
        public string identitycard { get; set; }
        [Required(ErrorMessage = "Bank Account field is required")]
        public string bank_account { get; set; }
        [Required(ErrorMessage = "Notepad field is required")]
        public string notepad { get; set; }
        [Required(ErrorMessage = "Pen field is required")]
        public string pen { get; set; }
        [Required(ErrorMessage = "Employee Card field is required")]
        public string employee_card { get; set; }
        [Required(ErrorMessage = "Admin any other field is required")]
        public string admin_anyother { get; set; }
        [Required(ErrorMessage = "Computer System field is required")]
        public string computer_system { get; set; }
        [Required(ErrorMessage = "Headphones field is required")]
        public string headphones { get; set; }
        [Required(ErrorMessage = "EmailId/Password field is required")]
        public string emailid_password { get; set; }
        [Required(ErrorMessage = "Network IP field is required")]
        public string network_ip { get; set; }
        [Required(ErrorMessage = "Firewall ID field is required")]
        public string firewall_id { get; set; }
        [Required(ErrorMessage = "Domain Username/Password field is required")]
        public string domain_usernamepassword { get; set; }
        [Required(ErrorMessage = "Messenger Access field is required")]
        public string messengers_access { get; set; }
        [Required(ErrorMessage = "System Admin any other field is required")]
        public string systemadmin_anyother { get; set; }
        [Required(ErrorMessage = "HR Manual and ISMS Responsibilities field is required")]
        public string hrmanual_and_responsibilities { get; set; }

        public virtual employee_detailsModel employee_details { get; set; }
    }
}
