//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class additional_information
    {
        public int additionalinformation_id { get; set; }
        public int employee_id { get; set; }
        public string known_to_presentemployee { get; set; }
        public string name_of_knownemployee { get; set; }
        public string relationship_with_knownemployee { get; set; }
    
        public virtual employee_details employee_details { get; set; }
    }
}
