//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class epfo_details
    {
        public int epfo_id { get; set; }
        public int employee_id { get; set; }
        public string presentcompany_pfnumber { get; set; }
        public string member_of_epfoscheme { get; set; }
        public string member_of_epsscheme { get; set; }
        public string universal_account_number { get; set; }
        public string prev_pf_acc_number { get; set; }
        public string scheme_certificate_number { get; set; }
        public string ppo_number { get; set; }
        public string international_worker { get; set; }
        public string country_of_origin { get; set; }
    
        public virtual employee_details employee_details { get; set; }
    }
}
