//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int roleID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> InfrastructureCost { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<decimal> PerDeskCost { get; set; }
    }
}
