//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cygnet.ProjMan.EFData.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department()
        {
            this.additional_information = new HashSet<additional_information>();
            this.employee_details = new HashSet<employee_details>();
        }
    
        public int DeptID { get; set; }
        public string DeptName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IncrementPeriod { get; set; }
        public string DeptCode { get; set; }
        public Nullable<bool> IsMultipleShift { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public string LookedByEmp { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<additional_information> additional_information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_details> employee_details { get; set; }
    }
}
