//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cygnet.ProjMan.EFData.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_refcheck
    {
        public int refcheck_id { get; set; }
        public int employee_id { get; set; }
        public string previous_company_name { get; set; }
        public string previous_company_address { get; set; }
        public string details_furnished_by { get; set; }
        public string designation { get; set; }
        public string department { get; set; }
        public string reporting_to { get; set; }
        public string reporting_designation { get; set; }
        public Nullable<decimal> monthly_salary { get; set; }
        public string reason_for_leaving { get; set; }
        public string attendence { get; set; }
        public string re_hire_status { get; set; }
        public string verified_by_name { get; set; }
        public Nullable<System.DateTime> verified_by_date { get; set; }
    
        public virtual employee_details employee_details { get; set; }
    }
}
