//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cygnet.ProjMan.EFData.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class prev_employ_4
    {
        public int prevemploy_id { get; set; }
        public int employee_id { get; set; }
        public string employers_name { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> periodworked_from { get; set; }
        public Nullable<System.DateTime> periodworked_to { get; set; }
        public string reason_of_leaving { get; set; }
    
        public virtual employee_details employee_details { get; set; }
    }
}
